<div class="page-content page-anim" id="page-dispen-siswa" style="display:none">
    <div class="page-header" style="margin-bottom:20px"><div><div class="page-title" style="font-size:22px;font-weight:800">Dispensasi Siswa</div><div class="page-subtitle">Buat dan pantau izin dispensasi siswa dengan persetujuan Waka dan Guru Piket.</div></div></div>
    <div class="card" style="padding:22px 24px;max-width:900px">
        <div class="card-header" style="margin-bottom:16px"><div class="card-title">Buat Permintaan Dispensasi</div></div>
        <form id="dispen-form" onsubmit="buatDispen(event)">@csrf
            <div style="display:grid;grid-template-columns:1fr 180px;gap:14px;margin-bottom:14px"><div><label for="dispen-siswa">Siswa</label><select id="dispen-siswa" name="id_siswa" class="filter-select" required style="width:100%;margin-top:4px"><option value="">Pilih siswa</option>@foreach($siswaAktif as $siswa)<option value="{{ $siswa->id_siswa }}">{{ $siswa->nama_siswa }} - {{ $siswa->kelas->nama_kelas ?? '-' }}</option>@endforeach</select></div><div><label for="dispen-tanggal">Tanggal</label><input id="dispen-tanggal" type="date" name="tanggal_dispen" value="{{ now()->toDateString() }}" class="filter-input" required style="width:100%;margin-top:4px"></div></div>
            <div style="margin-bottom:14px"><label for="dispen-alasan">Alasan dispensasi</label><textarea id="dispen-alasan" name="alasan" class="filter-input" rows="3" maxlength="2000" required placeholder="Contoh: mengikuti lomba, kegiatan sekolah, atau keperluan resmi lainnya..." style="width:100%;margin-top:4px;resize:vertical"></textarea></div>
            <button type="submit" class="btn-primary" style="border-radius:8px;padding:10px 16px;font-size:13px">Buat Link Persetujuan</button>
        </form>
        <div id="dispen-links" style="display:none;margin-top:16px;background:#eff6ff;border:1px solid #bfdbfe;border-radius:9px;padding:14px"><strong style="display:block;font-size:12px;color:#1d4ed8;margin-bottom:10px">Link persetujuan Waka</strong><div style="display:flex;gap:8px;align-items:center"><input id="dispen-waka-link" class="filter-input" readonly style="flex:1;font-size:12px"><button type="button" class="btn-secondary" onclick="salinDispen('dispen-waka-link')">Salin</button></div></div>
    </div>
    <div class="card" style="padding:22px 24px;margin-top:20px"><div class="card-header" style="margin-bottom:16px"><div class="card-title">Status Dispensasi</div></div><div style="overflow-x:auto"><table class="data-table" style="min-width:850px"><thead><tr><th>Siswa</th><th>Kelas</th><th>Tanggal</th><th>Alasan</th><th>Status Waka</th><th>Link Waka</th></tr></thead><tbody>@forelse($dispenTerbaru as $item)<tr><td><strong>{{ $item->siswa->nama_siswa ?? '-' }}</strong></td><td>{{ $item->siswa->kelas->nama_kelas ?? '-' }}</td><td>{{ $item->tanggal_dispen->format('d-m-Y') }}</td><td>{{ $item->alasan }}</td><td>{{ ucfirst($item->status_waka) }}</td><td><a href="{{ URL::temporarySignedRoute('dispen-siswa.public', now()->addDays(2), ['dispen' => $item->id_dispen_siswa, 'role' => 'waka']) }}" target="_blank">Buka Waka</a></td></tr>@empty<tr><td colspan="6" style="text-align:center;color:#64748b;padding:22px">Belum ada permintaan dispensasi.</td></tr>@endforelse</tbody></table></div></div>
</div>
<script>
function buatDispen(event){event.preventDefault();fetch(@json(route('dispen-siswa.store')),{method:'POST',headers:{'X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content,'Accept':'application/json'},body:new FormData(document.getElementById('dispen-form'))}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.message||'Gagal membuat dispensasi.');return d}).then(d=>{document.getElementById('dispen-waka-link').value=d.waka_link;document.getElementById('dispen-links').style.display='block';Swal.fire({icon:'success',title:'Link berhasil dibuat',text:d.message,confirmButtonColor:'#ea580c'})}).catch(e=>Swal.fire({icon:'error',title:'Gagal',text:e.message,confirmButtonColor:'#dc2626'}));}
function salinDispen(id){navigator.clipboard.writeText(document.getElementById(id).value).then(()=>Swal.fire({icon:'success',title:'Link disalin',timer:1200,showConfirmButton:false}));}
</script>
