<div class="page-content page-anim" id="page-izin-guru" style="display:none">
    <div class="page-header" style="margin-bottom:20px">
        <div><div class="page-title" style="font-size:22px;font-weight:800">Permintaan Izin Guru</div><div class="page-subtitle">Kirim permintaan izin untuk mendapatkan persetujuan Kepsek dan Waka.</div></div>
    </div>
    <div class="card" style="padding:22px 24px;max-width:900px">
        <div class="card-header" style="margin-bottom:16px"><div class="card-title">Buat Permintaan Izin</div></div>
        <form id="izin-guru-form" onsubmit="buatLinkIzinGuru(event)">@csrf
            @if($isGuruPiket)
                <div style="display:grid;grid-template-columns:1fr 180px;gap:14px;margin-bottom:14px"><div><label for="izin-id-guru">Guru yang meminta izin</label><select id="izin-id-guru" name="id_guru" class="filter-select" required style="width:100%;margin-top:4px"><option value="">Pilih guru</option>@foreach($guruAktif as $guruPilihan)<option value="{{ $guruPilihan->id_guru }}">{{ $guruPilihan->nama_guru }}</option>@endforeach</select></div><div><label for="izin-tanggal">Tanggal izin</label><input type="date" id="izin-tanggal" name="tanggal_izin" class="filter-input" value="{{ now()->toDateString() }}" required style="width:100%;margin-top:4px"></div></div>
            @else
                <div style="display:grid;grid-template-columns:1fr 180px;gap:14px;margin-bottom:14px"><div><label>Guru yang meminta izin</label><input type="text" class="filter-input" value="{{ session('auth_nama_guru') }}" readonly style="width:100%;margin-top:4px;background:#f8fafc"></div><div><label for="izin-tanggal">Tanggal izin</label><input type="date" id="izin-tanggal" name="tanggal_izin" class="filter-input" value="{{ now()->toDateString() }}" required style="width:100%;margin-top:4px"></div></div>
            @endif
            <div style="margin-bottom:14px"><label for="izin-alasan">Alasan izin</label><textarea id="izin-alasan" name="alasan" class="filter-input" rows="3" required maxlength="2000" placeholder="Tuliskan alasan tidak dapat mengajar..." style="width:100%;margin-top:4px;resize:vertical"></textarea></div>
            <button type="submit" class="btn-primary" style="border-radius:8px;padding:10px 16px;font-size:13px">Buat Link Persetujuan</button>
        </form>
        <div id="izin-link-result" style="display:none;margin-top:16px;background:#eff6ff;border:1px solid #bfdbfe;border-radius:9px;padding:14px"><div style="font-size:12px;font-weight:700;color:#1d4ed8;margin-bottom:10px">Link persetujuan terpisah</div><div style="display:grid;gap:8px"><div style="display:flex;gap:8px;align-items:center"><strong style="width:58px;font-size:12px">Kepsek</strong><input id="izin-kepsek-link" class="filter-input" readonly style="flex:1;font-size:12px"><button type="button" class="btn-secondary" onclick="salinLinkIzin('izin-kepsek-link')" style="font-size:12px">Salin</button></div><div style="display:flex;gap:8px;align-items:center"><strong style="width:58px;font-size:12px">Waka</strong><input id="izin-waka-link" class="filter-input" readonly style="flex:1;font-size:12px"><button type="button" class="btn-secondary" onclick="salinLinkIzin('izin-waka-link')" style="font-size:12px">Salin</button></div></div></div>
    </div>
    <div class="card" style="padding:22px 24px;margin-top:20px"><div class="card-header" style="margin-bottom:16px"><div class="card-title">Status Permintaan Izin</div></div><div style="overflow-x:auto"><table class="data-table" style="min-width:980px"><thead><tr><th>Guru</th><th>Tanggal</th><th>Alasan</th><th>Status Kepsek</th><th>Status Waka</th><th>Link</th></tr></thead><tbody>@forelse($izinGuruTerbaru as $izin)<tr><td><strong>{{ $izin->guru->nama_guru ?? '-' }}</strong></td><td>{{ $izin->tanggal_izin->format('d-m-Y') }}</td><td>{{ $izin->alasan }}</td><td>{{ ucfirst($izin->status_kepsek) }}</td><td>{{ ucfirst($izin->status_waka) }}</td><td><a href="{{ URL::temporarySignedRoute('izin-guru.public.role', now()->addDays(2), ['izin' => $izin->id_izin_guru, 'role' => 'kepsek']) }}" target="_blank" style="font-size:12px;margin-right:8px">Kepsek</a><a href="{{ URL::temporarySignedRoute('izin-guru.public.role', now()->addDays(2), ['izin' => $izin->id_izin_guru, 'role' => 'waka']) }}" target="_blank" style="font-size:12px">Waka</a></td></tr>@empty<tr><td colspan="6" style="text-align:center;color:#64748b;padding:22px">Belum ada permintaan izin.</td></tr>@endforelse</tbody></table></div></div>
</div>
<script>
function buatLinkIzinGuru(event) { event.preventDefault(); fetch(@json($isGuruPiket ? route('izin-guru.store') : route('guru.izin-guru.store')), {method:'POST', headers:{'X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content,'Accept':'application/json'}, body:new FormData(document.getElementById('izin-guru-form'))}).then(async response => { const result = await response.json(); if (!response.ok) throw new Error(result.message || 'Permintaan gagal dibuat.'); return result; }).then(result => { document.getElementById('izin-kepsek-link').value = result.kepsek_link; document.getElementById('izin-waka-link').value = result.waka_link; document.getElementById('izin-link-result').style.display = 'block'; Swal.fire({icon:'success',title:'Link berhasil dibuat',text:result.message,confirmButtonColor:'#ea580c'}); }).catch(error => Swal.fire({icon:'error',title:'Gagal',text:error.message,confirmButtonColor:'#dc2626'})); }
function salinLinkIzin(inputId) { navigator.clipboard.writeText(document.getElementById(inputId).value).then(() => Swal.fire({icon:'success',title:'Link disalin',timer:1200,showConfirmButton:false})); }
</script>
