<div class="page-content page-anim" id="page-izin-guru" style="display:none">
    <div class="page-header" style="margin-bottom:20px"><div><div class="page-title" style="font-size:22px;font-weight:800">Permintaan Izin Guru</div><div class="page-subtitle">Ajukan izin kepada Kepsek dan Waka. Status persetujuan dapat dipantau di halaman ini.</div></div></div>
    <div class="card" style="padding:22px 24px;max-width:900px">
        <div class="card-header" style="margin-bottom:16px"><div class="card-title">Buat Permintaan Izin</div></div>
        <form id="izin-guru-form" onsubmit="buatPermintaanIzinGuru(event)">@csrf
            <div style="display:grid;grid-template-columns:1fr 180px;gap:14px;margin-bottom:14px"><div><label>Guru yang meminta izin</label><input type="text" class="filter-input" value="{{ session('auth_nama_guru') ?? $guruAktif->firstWhere('id_guru', session('auth_guru_id'))?->nama_guru ?? '-' }}" readonly style="width:100%;margin-top:4px;background:#f8fafc"></div><div><label for="guru-izin-tanggal">Tanggal izin</label><input type="date" id="guru-izin-tanggal" name="tanggal_izin" class="filter-input" value="{{ now()->toDateString() }}" required style="width:100%;margin-top:4px"></div></div>
            <div style="margin-bottom:14px"><label for="guru-izin-alasan">Alasan izin</label><textarea id="guru-izin-alasan" name="alasan" class="filter-input" rows="4" required maxlength="2000" placeholder="Tuliskan alasan tidak dapat mengajar..." style="width:100%;margin-top:4px;resize:vertical"></textarea></div>
            <div style="margin-bottom:14px"><label for="guru-izin-foto">Foto surat (opsional)</label><input type="file" id="guru-izin-foto" name="foto_surat" accept="image/jpeg,image/png,image/webp" style="display:block;width:100%;margin-top:6px;font-size:13px"><small style="display:block;color:#64748b;margin-top:5px">Format JPG, PNG, atau WEBP. Maksimal 5 MB.</small></div>
            <button type="submit" class="btn-primary" style="border-radius:8px;padding:10px 16px;font-size:13px">Buat Link Persetujuan</button>
        </form>
        <div id="guru-izin-link-result" style="display:none;margin-top:16px;background:#eff6ff;border:1px solid #bfdbfe;border-radius:9px;padding:14px"><strong style="display:block;font-size:12px;color:#1d4ed8;margin-bottom:10px">Link persetujuan siap dibagikan</strong><div style="display:grid;gap:8px"><div style="display:flex;gap:8px;align-items:center"><strong style="width:58px;font-size:12px">Kepsek</strong><input id="guru-izin-kepsek-link" class="filter-input" readonly style="flex:1;font-size:12px"><button type="button" class="btn-secondary" onclick="salinPermintaanIzin('guru-izin-kepsek-link')">Salin</button></div><div style="display:flex;gap:8px;align-items:center"><strong style="width:58px;font-size:12px">Waka</strong><input id="guru-izin-waka-link" class="filter-input" readonly style="flex:1;font-size:12px"><button type="button" class="btn-secondary" onclick="salinPermintaanIzin('guru-izin-waka-link')">Salin</button></div></div></div>
    </div>
    <div class="card" style="padding:22px 24px;margin-top:20px"><div class="card-header" style="margin-bottom:16px"><div class="card-title">Data dan Status Izin Saya</div></div><div style="overflow-x:auto"><table class="data-table" style="min-width:950px"><thead><tr><th>Tanggal</th><th>Alasan</th><th>Surat</th><th>Status Kepsek</th><th>Status Waka</th><th>Status Akhir</th></tr></thead><tbody>@forelse($izinGuruTerbaru as $izin)<tr><td>{{ $izin->tanggal_izin->format('d-m-Y') }}</td><td>{{ $izin->alasan }}</td><td>@if($izin->foto_surat)<a href="{{ Storage::disk('public')->url($izin->foto_surat) }}" target="_blank" rel="noopener">Lihat foto</a>@else<span style="color:#94a3b8">Tidak ada</span>@endif</td><td>{{ ucfirst($izin->status_kepsek) }}</td><td>{{ ucfirst($izin->status_waka) }}</td><td>@if($izin->isDisetujui())<span class="badge badge-success">Diterima</span>@elseif($izin->status_kepsek === 'ditolak' || $izin->status_waka === 'ditolak')<span class="badge badge-danger">Ditolak</span>@else<span class="badge badge-warning">Menunggu</span>@endif</td></tr>@empty<tr><td colspan="6" style="text-align:center;color:#64748b;padding:22px">Belum ada data izin.</td></tr>@endforelse</tbody></table></div></div>
</div>
<script>
function buatPermintaanIzinGuru(event){event.preventDefault();fetch(@json(route('guru.izin-guru.store')),{method:'POST',headers:{'X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content,'Accept':'application/json'},body:new FormData(document.getElementById('izin-guru-form'))}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.message||'Permintaan izin gagal dibuat.');return d}).then(d=>{document.getElementById('guru-izin-kepsek-link').value=d.kepsek_link;document.getElementById('guru-izin-waka-link').value=d.waka_link;document.getElementById('guru-izin-link-result').style.display='block';Swal.fire({icon:'success',title:'Permintaan berhasil dibuat',text:d.message,confirmButtonColor:'#2563eb'});}).catch(e=>Swal.fire({icon:'error',title:'Gagal',text:e.message,confirmButtonColor:'#dc2626'}));}
function salinPermintaanIzin(id){navigator.clipboard.writeText(document.getElementById(id).value).then(()=>Swal.fire({icon:'success',title:'Link disalin',timer:1200,showConfirmButton:false}));}
</script>
